#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing RVM (Ruby Version Manager) ..."
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc
# RVM
[[ $SHELL == "/bin/zsh" ]] && shellrc="~/.zshrc"
[[ $SHELL == "/bin/bash" ]] && shellrc="~/.bashrc"
[[ -s "/Users/`whoami`/.rvm/scripts/rvm" ]] && source "/Users/`whoami`/.rvm/scripts/rvm"" >> $shellrc
  source $shellrc

#Ruby
echo "Installing Ruby 1.9.3 ..."
  rvm install 1.9.3
  rvm use 1.9.3 --default
  rvm 1.9.3@rails32 --default
#Set Gem Sources, Using TaoBao's gem sources.
  gem sources --remove http://rubygems.org/
  gem sources -a http://ruby.taobao.org/
#Install rails
echo "Installing Rails..."
  gem install rails 