#!/usr/bin/env bash


echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Postgres, a good open source relational database ..."
  sudo apt-get install postgresql

echo "Installing Redis, a good key-value database ..."
  sudo apt-get install redis

echo "Installing ack, a good way to search through files ..."
  sudo apt-get install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  sudo apt-get install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  sudo apt-get install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  sudo apt-get install qt

echo "Installing RVM (Ruby Version Manager) ..."
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo "
# RVM
[[ $SHELL == "/bin/zsh" ]] && shellrc="~/.zshrc"
[[ $SHELL == "/bin/bash" ]] && shellrc="~/.bashrc"
[[ -s "/home/$HOME/.rvm/scripts/rvm" ]] && source "/home/$HOME/.rvm/scripts/rvm"" >> $shellrc
  source $shellrc

bash < <(curl -s https://raw.github.com/fenprace/laptop-china/master/ruby)
bash < <(curl -s https://raw.github.com/fenprace/laptop-china/master/heroku)
